### ISSUE TITLE
Getting error "apache2: Could not reliably determine the server's fully qualified domain name"

### ISSUE THREAD

**Issue by JJena** [cemtan/sar2html#1]
Hi,
When I run the docker image with below command (Ubuntu), I'm getting the error:
docker run -p 80:80 cemtan/sar2html:v3.2.1

**Error:**
Status: Downloaded newer image for cemtan/sar2html:v3.2.1
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Feb 24 17:45:03.558021 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.1.20 configured -- resuming normal operations
[Mon Feb 24 17:45:03.558093 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Feb 24 17:45:11.489179 2020] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully

**Comment by cemtan** [comment]
Try running by following command:
docker run -p 80:80 -h sar2html.localdomain cemtan/sar2html:v3.2.1
