### ISSUE TITLE
500 Internal Server error when running on Windows docker desktop with a shared directory

### ISSUE THREAD

**Issue by mdeggers** [cemtan/sar2html#5]
I'm trying to run this on a Windows 10 Professional platform with Docker Desktop 20.10.16 and use a shared directory.

I'm able to mount the directory with:

 docker run -p 5000:5000 -v j:\sar2html:/sar2html/data -d -h sar2html.localdomain cemtan/sar2html:4.0.0

The db files get written in the db directory. When I upload a tar.gz file, this also gets uploaded to the tmp directory. It appears to be unpacked correctly.

At that point, the browser returns the 500 Internal Server error.

Is there a place where I can look to find any error logs?

The platform works great when I don't use a shared directory.

**Comment by cemtan** [comment]
If you run docker container without -d switch you may see the error message in the console you run the container.
I did not encounter any problem like that. Maybe it is windows related. I never check the tools on the windows docker .
If you share your tar.gz file with me I can check.

**Comment by mdeggers** [comment]
I'll take a look at it in the morning. I will capture the output without -d as well as send you the tar.gz file.

The tar.gz file works fine as long as I don't try to persist the information on a Windows-based share. I also normally work on Linux platforms, so I am looking at running this stand-alone with a proxy Apache HTTPD server sitting in front of it.

Thanks for the response, and I'll do what I can to help out, especially since I'm the one reporting the issue.

**Comment by mdeggers** [comment]
I managed to capture the output from the command as well as did a listing of the created directory structure. I've included the following files:

- sar2html-vol.txt (command execution)
- vol-listing.txt (directory listing after command execution)
- .gz file (file generated from old sar2ascii shell script on the remote system

The host did not appear on the start page when rerunning the docker command.
[sar2html-vol.txt](https://github.com/cemtan/sar2html/files/6540571/sar2html-vol.txt)
[vol-listing.txt](https://github.com/cemtan/sar2html/files/6540573/vol-listing.txt)
[sar2html-vcprod01.sf.visualcalc.com-2105240953.tar.gz](https://github.com/cemtan/sar2html/files/6540583/sar2html-vcprod01.sf.visualcalc.com-2105240953.tar.gz)

**Comment by cemtan** [comment]
It seems that the original error has been masked since some files left behind in tmp folder because of the previous error.
Please clean tmp folder and try to upload your report again. If it fails please let me see the logs.
I tested your report with and without persistent volume. no error so far....

Thanks,
Cem

**Comment by mdeggers** [comment]
I do normally clean out the directory. Here's the process:

1. delete everything in J:\sar2html
2. run the docker image with the attached volume
3. get the 500 Internal server error
4. stop the container
5. delete the container

I've attached the following files

- before-start.txt - directory listing before start
- before-upload.txt - directory listing after start, but before upload
- after-upload.txt - directory listing after upload
- sar2html-vol.txt - output from docker command

[before-upload.txt](https://github.com/cemtan/sar2html/files/6541272/before-upload.txt)
[after-upload.txt](https://github.com/cemtan/sar2html/files/6541273/after-upload.txt)
[before-start.txt](https://github.com/cemtan/sar2html/files/6541274/before-start.txt)
[sar2html-vol.txt](https://github.com/cemtan/sar2html/files/6541275/sar2html-vol.txt)

**Comment by cemtan** [comment]
I was able to repeat the problem.

Here is the log file:
[2021-05-25 17:43:25,082] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "sar2html.py", line 379, in uploadFiles
    updateThread = AppContextThread(target=updateDb(hostList, app.config['UPLOAD_FOLDER']))
  File "sar2html.py", line 100, in updateDb
    s2df.columns = s2col
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 5 elements, new values have 4 elements

Windows share does conflicts with file upload somehow.
I think moving tmp from data folder to root of sar2html would fix the problem. 
Let me see!

**Comment by cemtan** [comment]
https://github.com/cemtan/sar2html/pull/9

**Comment by mdeggers** [comment]
Thanks. This seems to work (and remember uploaded files). I apologize for not replying sooner. I had a nearly 24 hour power outage.

Again, thanks for the fine work!
